version: '3'

services:
  hh-ru-auto-resume-raising-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: mitetenov/hh-ru-auto-resume-raising-bot:latest
    volumes:
      - ./.env:/.env
    restart: unless-stopped